### ISSUE TITLE
Modèles UNFPA/EPI

### ISSUE THREAD

**Issue by rgaudin** [yeleman/pnlp2011#9]
- Deplacer modeles FNUAP/EPI dans snisi_core
- Modifier/vérifier les raports aggregés pour UNFPA
- Créer rapport aggregés pour EPI

**Comment by alou** [comment]
- Models FNUAP/EPI ont été déplacé dans snisi_core
- les rapports aggregés pour UNFPA ont été modifié mais pas vérifie
- Le rapport aggregé pour EPI a été créé, il n'a pas été testé
